# Generated by Django 3.2.7 on 2021-10-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamplatform',
            name='about',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='storyline',
            field=models.TextField(max_length=2048),
        ),
    ]
