# Generated by Django 3.2.7 on 2021-10-06 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_review_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='platforms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='app.streamplatform'),
        ),
    ]
