# Generated by Django 3.2.7 on 2021-10-07 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_watchlist_platforms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='platforms',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='platforms',
            field=models.ManyToManyField(related_name='watchlist', to='app.StreamPlatform'),
        ),
    ]
