# Generated by Django 3.2.7 on 2021-10-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211007_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='number_rating',
        ),
    ]
